version: "3"
services:
    test_service:
        image: minhthucdao1/test
        command: /bin/sh -c "/dao_wp/run_from_bind_mount.sh"
        volumes:
          - shared_data:/dao_wp/
volumes:
    shared_data:
      name: "${SHARED_DATA}"



