image:
	docker build --network=host -t minhthucdao1/test .
test:
	docker run --rm -it minhthucdao1/test /bin/sh
run:
	docker run --rm -it minhthucdao1/test /dao_wp/run.sh
push:
	docker push minhthucdao1/test
