name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run_test:
    name: Run test
    runs-on: ubuntu-20.04
    steps:
        - name: Check out repository code
          uses: actions/checkout@v3
        - name : Run test
          run: docker-compose -f docker/docker-compose.yml up
 

