name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run_test:
    name: Run test
    runs-on: ubuntu-20.04
    steps:
        - name : Run test
          run: echo "finish"
 

