name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run_test:
    name: Run test
    runs-on: ubuntu-20.04
    container: 
        image: docker/compose:debian-1.29.2
        volumes: 
            - shared_data:/share_data  
    steps:
        - name: Check out repository code
          uses: actions/checkout@v3
        - name: Run test
          run: |
            cp docker/run_from_bind_mount.sh /share_data/
            docker-compose -f docker/docker-compose.yml up
 

